<?php include_once(__DIR__ . "/../../../config.php"); ?>


<!doctype html>
<html lang="en">
<head>
    <?php include_once(__DIR__ . "/../../part/admin/head.phtml"); ?>
</head>
<body>
    <?php include_once(__DIR__ . "/../../part/admin/navbar.phtml"); ?>

    <div class="py-5">
        <div class="container">
            <h1 class="mb-5"> Admin Dashboard </h1>
        </div>
    </div>

    <?php include_once(__DIR__ . "/../../part/admin/script.phtml"); ?>
</body>
</html>
