<?php include_once(__DIR__ . "/../../../config.php"); ?>


<!doctype html>
<html lang="en">
<head>
    <?php include_once(__DIR__ . "/../../part/admin/head.phtml"); ?>
</head>
<body>
    <form class="py-5" action="<?php print($base_url . "/admin/login-submit.php") ?>" method="post">
        <div class="container mw-360px">
            <h1 class="mb-5"> Admin Login </h1>

            <div class="mb-3">
                <label for="username" class="form-label"> Username </label>
                <input type="text" class="form-control" name="username" pattern="\w{2,32}" value="<?php if (isset($_SESSION["submitted-username"])) /* then */ print($_SESSION["submitted-username"]) ?>" id="username" required />
            </div>
            <div class="mb-4">
                <label for="password" class="form-label"> Password </label>
                <input type="password" class="form-control" name="password" pattern="[\w!@#$%^&*]{8,32}" value="<?php if (isset($_SESSION["submitted-password"])) /* then */ print($_SESSION["submitted-password"]) ?>" id="password" required />
            </div>

        <?php if (isset($error_message)) { ?>
            <div class="mb-4 text-danger">
                <?php print($error_message); ?>
            </div>
        <?php } ?>

            <button type="submit" class="btn btn-primary" name="submit" value="submit"> Log in </button>
            <button type="reset" class="btn btn-secondary" name="reset"> Reset </button>
        </div>
    </form>


    <?php include_once(__DIR__ . "/../../part/admin/script.phtml"); ?>
</body>
</html>
