<!doctype html>
<html lang="en">
<head>
    <?php include_once(__DIR__ . "/../../../part/admin/head.phtml"); ?>
</head>
<body>
    <?php include_once(__DIR__ . "/../../../part/admin/navbar.phtml"); ?>

    <div class="py-5">
        <div class="container">
            <h1 class="mb-5"> Attendance Index </h1>

            <table class="table">
                <thead>
                    <tr>
                        <th scope="col"> Event </th>
                        <th scope="col"> Visitor </th>
                        <th scope="col"> Phone </th>
                        <th scope="col"> Email </th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($all_attendances_joined as $attendance_joined) { ?>
                    <tr>
                        <td>
                            <a class="text-decoration-none" href="<?php print($base_url . "/event.php?id=" . $attendance_joined->event->get_id()) ?>" target="_blank"> <?php print($attendance_joined->event->get_name()) ?> </a>
                        </td>
                        <td>
                            <a class="text-decoration-none" href="<?php print($base_url . "/admin/visitor") ?>" target="_blank"> <?php print($attendance_joined->visitor->get_fullname()) ?> </a>
                        </td>
                        <td> <?php print($attendance_joined->visitor->get_phone()) ?> </td>
                        <td> <?php print($attendance_joined->visitor->get_email()) ?> </td>
                    </tr>
                <?php } // foreach ?>
                </tbody>
            </table>
        </div>
    </div>

    <?php include_once(__DIR__ . "/../../../part/admin/script.phtml"); ?>
</body>
</html>
