<?php include_once(__DIR__ . "/../../config.php"); ?>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src=<?php print($base_url . "/public/js/jquery.richtext.min.js"); ?>></script>
<script src=<?php print($base_url . "/public/js/visitor.js"); ?>></script>
