<?php include_once(__DIR__ . "/../../../../config.php"); ?>


<!doctype html>
<html lang="en">
<head>
    <?php include_once(__DIR__ . "/../../../part/admin/head.phtml"); ?>
</head>
<body>
    <?php include_once(__DIR__ . "/../../../part/admin/navbar.phtml"); ?>

    <form class="py-5" action=<?php print($base_url . "/admin/event/add-submit.php") ?> method="post">
        <div class="container mw-720px">
            <h1 class="mb-5"> Add Event </h1>

            <div class="mb-3">
                <div class="mb-1"> For </div>

                <input class="form-check-input" type="radio" name="kids-only" value="1" id="children" checked />
                <label class="form-check-label" for="children"> Children </label>

                &nbsp; &nbsp; &nbsp;

                <input class="form-check-input" type="radio" name="kids-only" value="0" id="everyone" />
                <label class="form-check-label" for="everyone"> Everyone </label>
            </div>

            <div class="mb-3 mw-360px">
                <label for="name" class="form-label"> Name </label>
                <input type="text" class="form-control" name="name" id="name" required />
            </div>

            <div class="mb-3">
                <label for="description" class="form-label"> Description </label>
                <textarea class="form-control" name="description" rows="6" id="description" required></textarea>
            </div>

            <div class="mb-3 mw-360px">
                <label for="image-url" class="form-label"> Image URL </label>
                <input type="text" class="form-control" name="image-url" id="image-url" required />
            </div>

            <div class="mb-4 mw-360px">
                <label for="starting-time" class="form-label"> Starting time </label>
                <input type="datetime-local" class="form-control" name="starting-time" id="starting-time" required />
            </div>

            <button type="submit" class="btn btn-primary" name="submit" value="submit"> Submit </button>
            <button type="reset" class="btn btn-secondary" name="reset"> Reset </button>
        </div>
    </form>

    <?php include_once(__DIR__ . "/../../../part/admin/script.phtml"); ?>
</body>
</html>
