<?php include_once(__DIR__ . "/../../../../config.php"); ?>


<!doctype html>
<html lang="en">
<head>
    <?php include_once(__DIR__ . "/../../../part/admin/head.phtml"); ?>
</head>
<body>
    <?php include_once(__DIR__ . "/../../../part/admin/navbar.phtml"); ?>

    <div class="py-5">
        <div class="container">
            <h1 class="mb-5"> Deleted Event </h1>

            <table class="table">
                <tbody>
                    <tr>
                        <th scope="row"> Id </th>
                        <td> <?php print($event->get_id()) ?> </td>
                    </tr>
                    <tr>
                        <th scope="row"> For </th>
                        <td> <?php print($event->get_kids_only() ? "Children" : "Everyone") ?> </td>
                    </tr>
                    <tr>
                        <th scope="row"> Name </th>
                        <td> <?php print($event->get_name()) ?> </td>
                    </tr>
                    <tr>
                        <th scope="row"> Description </th>
                        <td> <?php print($event->get_description()) ?> </td>
                    </tr>
                    <tr>
                        <th scope="row"> Image URL </th>
                        <td> <?php print($event->get_image_url()) ?> </td>
                    </tr>
                    <tr>
                        <th scope="row"> Starting time </th>
                        <td> <?php print(str_replace("CET", "T", $event->get_starting_time())) ?> </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <?php include_once(__DIR__ . "/../../../part/admin/script.phtml"); ?>
</body>
</html>
