<?php include_once(__DIR__ . "/../../../../config.php"); ?>


<!doctype html>
<html lang="en">
<head>
    <?php include_once(__DIR__ . "/../../../part/admin/head.phtml"); ?>
</head>
<body>
    <?php include_once(__DIR__ . "/../../../part/admin/navbar.phtml"); ?>

    <form class="py-5" action=<?php print($base_url . "/admin/specie/add-submit.php") ?> method="post">
        <div class="container mw-360px">
            <h1 class="mb-5"> Add Specie </h1>

            <div class="mb-3">
                <label for="name" class="form-label"> Name </label>
                <input type="text" class="form-control" id="name" name="name" required />
            </div>

            <div class="mb-3">
                <label for="description" class="form-label"> Description </label>
                <textarea class="form-control" name="description" rows="3" id="description" required></textarea>
            </div>

            <div class="mb-4">
                <label for="image-url" class="form-label"> Image URL </label>
                <input type="text" class="form-control" name="image-url" id="image-url" required />
            </div>

            <button type="submit" class="btn btn-primary" name="submit" value="submit"> Submit </button>
            <button type="reset" class="btn btn-secondary" name="reset"> Reset </button>
        </div>
    </form>

    <?php include_once(__DIR__ . "/../../../part/admin/script.phtml"); ?>
</body>
</html>
