<?php include_once(__DIR__ . "/../../../../config.php"); ?>


<!doctype html>
<html lang="en">
<head>
    <?php include_once(__DIR__ . "/../../../part/admin/head.phtml"); ?>
</head>
<body>
    <?php include_once(__DIR__ . "/../../../part/admin/navbar.phtml"); ?>

    <form class="py-5" action=<?php print($base_url . "/admin/specie/edit-submit.php") ?> method="post">
        <div class="container mw-360px">
            <h1 class="mb-5"> Add Specie </h1>

            <input type="hidden" name="id" value="<?php print($specie->get_id()) ?>">

            <div class="mb-3">
                <label for="name" class="form-label"> Name </label>
                <input type="text" class="form-control" id="name" name="name" value="<?php print($specie->get_name()) ?>" required />
            </div>

            <div class="mb-3">
                <label for="description" class="form-label"> Description </label>
                <textarea class="form-control" name="description" rows="6" id="description" required><?php print($specie->get_description()) ?></textarea>
            </div>

            <div class="mb-3">
                <label for="image-url" class="form-label"> Image URL </label>
                <input type="text" class="form-control" name="image-url" id="image-url" value="<?php print($specie->get_image_url()) ?>" required />
            </div>

            <div class="mb-4">
                <div class="mb-1"> Featured </div>

                <input class="form-check-input" type="radio" name="featured" value="1" id="yes" <?php if ($specie->get_featured()) /* then */ print("checked") ?> />
                <label class="form-check-label" for="yes"> Yes </label>

                &nbsp; &nbsp; &nbsp;

                <input class="form-check-input" type="radio" name="featured" value="0" id="no" <?php if (! $specie->get_featured()) /* then */ print("checked") ?> />
                <label class="form-check-label" for="no"> No </label>
            </div>

            <button type="submit" class="btn btn-primary" name="submit" value="submit"> Submit </button>
            <button type="reset" class="btn btn-secondary" name="reset"> Reset </button>
        </div>
    </form>

    <?php include_once(__DIR__ . "/../../../part/admin/script.phtml"); ?>
</body>
</html>
