<!doctype html>
<html lang="en">
<head>
    <?php include_once(__DIR__ . "/../../../part/admin/head.phtml"); ?>
</head>
<body>
    <?php include_once(__DIR__ . "/../../../part/admin/navbar.phtml"); ?>

    <div class="py-5">
        <div class="container">
            <h1 class="mb-5"> Specie Index </h1>

            <a class="btn btn-primary mb-3" href="<?php print($base_url . "/admin/specie/add.php") ?>"> Add Specie </a>

        <?php if (isset($error_message)) { ?>
            <div class="mb-2 text-danger">
                <?php print($error_message) ?>
            </div>
        <?php } // if ?>

            <table class="table">
                <thead>
                    <tr>
                        <th scope="col"> Id </th>
                        <th scope="col"> Name </th>
                        <th scope="col"> Description </th>
                        <th scope="col"> Image </th>
                        <th scope="col"> Featured </th>
                        <th scope="col"> Actions </th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($all_species as $specie) { ?>
                    <tr>
                        <th scope="row"> <?php print($specie->get_id()) ?> </th>
                        <td> <?php print($specie->get_name()) ?> </td>
                        <td> <?php print($specie->get_description()) ?> </td>
                        <td>
                            <a class="text-decoration-none" href="<?php print($specie->get_image_url()) ?>" target="_blank">
                                <img class="w-100px" src="<?php print($specie->get_image_url()) ?>" />
                            </a>
                        </td>
                        <td> <?php print($specie->get_featured() ? "Yes" : "No") ?> </td>
                        <td>
                            <div class="mb-1">
                                <a class="btn btn-light w-100px" href="<?php print($base_url . "/admin/specie/edit.php?id=" . $specie->get_id()) ?>">
                                    <i class="fas fa-edit"></i> Edit
                                </a>
                            </div>
                            <div>
                                <a class="btn btn-danger w-100px" href="<?php print($base_url . "/admin/specie/delete.php?id=" . $specie->get_id()) ?>">
                                    <i class="fas fa-trash-alt"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                <?php } // foreach ?>
                </tbody>
            </table>
        </div>
    </div>

    <?php include_once(__DIR__ . "/../../../part/admin/script.phtml"); ?>
</body>
</html>
