<?php include_once(__DIR__ . "/../../config.php") ?>


<!doctype html>
<html lang="en" dir="ltr">
<head>
    <?php include_once(__DIR__ . "/../part/head.phtml") ?>
</head>
<body>
    <?php include_once(__DIR__ . "/../part/header.phtml") ?>
    <?php include_once(__DIR__ . "/../part/navbar.phtml") ?>

    <form class="py-5" action="<?php print($base_url . "/login-submit.php") ?>" method="post">
        <div class="container mw-360px">
            <h1 class="mb-5"> Log In </h1>

            <div class="mb-3">
                <label for="username" class="form-label"> Username </label>
                <input type="text" class="form-control" name="username" pattern="\w{1,32}" id="username" required />
            </div>

            <div class="mb-4">
                <label for="password" class="form-label"> Password </label>
                <input type="password" class="form-control" name="password" pattern="[\w!@#$%^&*]{1,32}" id="password" required />
            </div>

        <?php if (isset($error_message)) { ?>
            <div class="mb-4 text-danger">
                <?php print($error_message); ?>
            </div>
        <?php } ?>

            <button type="submit" class="btn btn-primary" name="submit" value="submit"> Log In </button>
            <button type="reset" class="btn btn-secondary" name="reset"> Reset </button>
        </div>
    </form>

    <?php include_once(__DIR__ . "/../part/footer.phtml") ?>
    <?php include_once(__DIR__ . "/../part/script.phtml") ?>
</body>
</html>
