<!doctype html>
<html lang="en" dir="ltr">
<head>
    <?php include_once(__DIR__ . "/../part/head.phtml") ?>
</head>
<body>
    <?php include_once(__DIR__ . "/../part/header.phtml") ?>
    <?php include_once(__DIR__ . "/../part/navbar.phtml") ?>

    <div class="py-5">
        <div class="container mw-720px">
            <h1 class="mb-5"> <?php print($page->get_title()) ?> </h1>

            <div>
                <?php print($page->get_body_text()) ?>
            </div>
        </div>
    </div>

    <?php include_once(__DIR__ . "/../part/script.phtml") ?>
</body>
</html>
