<?php include_once(__DIR__ . "/../../../../config.php"); ?>


<!doctype html>
<html lang="en">
<head>
    <?php include_once(__DIR__ . "/../../../part/admin/head.phtml"); ?>
</head>
<body>
    <?php include_once(__DIR__ . "/../../../part/admin/navbar.phtml"); ?>

    <form class="py-5" action=<?php print($base_url . "/admin/page/add-submit.php") ?> method="post">
        <div class="container mw-360px">
            <h1 class="mb-5"> Add Page </h1>

            <div class="mb-3">
                <label for="menu-name" class="form-label"> Menu name </label>
                <input type="text" class="form-control" name="menu-name" value="<?php if(isset($_SESSION["submitted-menu-name"])) /* then */ print($_SESSION["submitted-menu-name"]) ?>" id="menu-name" required />
            </div>

            <div class="mb-3">
                <label for="title" class="form-label"> Title </label>
                <input type="text" class="form-control" name="title" value="<?php if(isset($_SESSION["submitted-title"])) /* then */ print($_SESSION["submitted-title"]) ?>" id="title" required />
            </div>

            <div class="mb-3">
                <label for="body-text" class="form-label"> Body text </label>
                <textarea class="form-control" name="body-text" rows="3" id="body-text" required><?php if(isset($_SESSION["submitted-body-text"])) /* then */ print($_SESSION["submitted-body-text"]) ?></textarea>
            </div>

            <div class="mb-4">
                <label for="order" class="form-label"> Order </label>
                <input type="number" class="form-control" name="order" step="1" value="<?php if(isset($_SESSION["submitted-order"])) /* then */ print($_SESSION["submitted-order"]) ?>" id="order" required />
            </div>

        <?php if (isset($add_error)) { ?>
            <div class="mb-4 text-danger">
                <?php print($add_error) ?>
            </div>
        <?php } // if ?>

            <button type="submit" class="btn btn-primary" name="submit" value="submit"> Submit </button>
            <button type="reset" class="btn btn-secondary" name="reset"> Reset </button>
        </div>
    </form>

    <?php include_once(__DIR__ . "/../../../part/admin/script.phtml"); ?>
</body>
</html>
