<?php include_once(__DIR__ . "/../../../../config.php"); ?>


<!doctype html>
<html lang="en">
<head>
    <?php include_once(__DIR__ . "/../../../part/admin/head.phtml"); ?>
</head>
<body>
    <?php include_once(__DIR__ . "/../../../part/admin/navbar.phtml"); ?>

    <div class="py-5">
        <div class="container">
            <h1 class="mb-5"> Deleted Page </h1>

            <table class="table">
                <tbody>
                    <tr>
                        <th scope="row"> Id </th>
                        <td> <?php print($page->get_id()) ?> </td>
                    </tr>
                    <tr>
                        <th scope="row"> Menu Name </th>
                        <td> <?php print($page->get_menu_name()) ?> </td>
                    </tr>
                    <tr>
                        <th scope="row"> Title </th>
                        <td> <?php print($page->get_title()) ?> </td>
                    </tr>
                    <tr>
                        <th scope="row"> Text body </th>
                        <td> <?php print(substr($page->get_body_text(), 0, 64) . "...") ?> </td>
                    </tr>
                    <tr>
                        <th scope="row"> Order </th>
                        <td> <?php print($page->get_order()) ?> </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <?php include_once(__DIR__ . "/../../../part/admin/script.phtml"); ?>
</body>
</html>
