<?php include_once(__DIR__ . "/../../../../config.php"); ?>


<!doctype html>
<html lang="en">
<head>
    <?php include_once(__DIR__ . "/../../../part/admin/head.phtml"); ?>
</head>
<body>
    <?php include_once(__DIR__ . "/../../../part/admin/navbar.phtml"); ?>

    <div class="py-5">
        <div class="container">
            <h1 class="mb-5"> Deleted Review </h1>

            <table class="table mw-720px">
                <tbody>
                    <tr>
                        <th scope="row"> Id </th>
                        <td> <?php print($review_joined->review->get_id()) ?> </td>
                    </tr>
                    <tr>
                        <th scope="row"> Visitor </th>
                        <td> <?php print($review_joined->visitor->get_fullname()) ?> </td>
                    </tr>
                    <tr>
                        <th scope="row"> Rating </th>
                        <td> <?php print($review_joined->review->get_rating()) ?>/10 </td>
                    </tr>
                    <tr>
                        <th scope="row"> Feedback </th>
                        <td> <?php print($review_joined->review->get_feedback()) ?> </td>
                    </tr>
                    <tr>
                        <th scope="row"> Datetime </th>
                        <td> <?php print($review_joined->review->get_submit_time()) ?> </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <?php include_once(__DIR__ . "/../../../part/admin/script.phtml"); ?>
</body>
</html>
